### ISSUE TITLE
What timezone is this?

### ISSUE THREAD

**Issue by daniel-box** [bahamas10/node-log-timestamp#5]
What time does this produce? I meant, Which timezone is this? Or does it produce the time i have locally? If the answer is the initial one, what steps should i take so i can convert it to my timezone? Thanks for the help! Im quite noob at node.js

**Comment by bahamas10** [comment]
The time it outputs by default is UTC; you can tell from the `Z` at the end of the timestamp.

In order to localize the timezone printed, you would need to provide a custom function. see:

``` js
> require('log-timestamp')(function() { return '[' + new Date().toISOString() + '] %s'; });
> console.log('hello')
[2017-04-05T15:29:13.295Z] hello

> require('log-timestamp')(function() { return '[' + new Date() + '] %s'; });
> console.log('hello')
[Wed Apr 05 2017 11:29:20 GMT-0400 (EDT)] hello
```

Notice the second timestamp is local to me (EDT)
